apiVersion: v1
kind: Service
metadata:
  name: sourceip
  labels:
    app: sourceip
spec:
  ports:
    - name: sourceip
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: sourceip